server:
  port: 8761

spring:
  application:
    name: eureka-server
  security:
    user:
      name: ${EUREKA_USER:admin}
      password: ${EUREKA_PASSWORD:admin}

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    # Standalone mode - don't register with itself
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    # Disable self-preservation in development (enable in production)
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:false}
    # Renewal interval for registry cache
    response-cache-update-interval-ms: 5000
    # How often to check for expired instances
    eviction-interval-timer-in-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
